In [ ]:
# NAME: Alan Luo
# Assignment: NLA_1 - 2.1 Data Manipulation
# Date: 09/07/2023
# Section: LEC002

In [ ]:
import torch

In [ ]:
# .arange(x, dtype) -> creating a vector of evenly spaced values, a "tensor"
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# .numel() -> counting the number of elements in the tensor
x.numel()

12

In [ ]:
# .shape -> shape of the tensor (length along each axis)
x.shape

torch.Size([12])

In [ ]:
# .reshape(x, y) -> reshaping the tensor to a different size
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# example of inferring second dimension using .reshape()
Y = x.reshape(3, -1)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# .zeros((x, y, z)) -> creating a tensor of all zeroes, of shape (x, y, z)
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# .ones((x, y, z)) -> creating a tensor of all ones, of shape (x, y, z)
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# .randn() -> creates tensor of size (x, y), sampling random elements on a probability distribution
torch.randn(3, 4)

tensor([[-0.2143,  0.2599, -0.0248,  2.6420],
        [-2.4359, -0.4827,  0.1078,  1.4204],
        [-0.5079, -0.8908,  0.4107,  0.6905]])

In [ ]:
# .tensor() -> creating a tensor, constructing a matrix representing a list of lists
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
# index slicing
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
# writing into the tensor by indexing
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# taking the first two rows, and every column
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
# .exp(x) -> elementwise operation, takes the e^x for each element (f: R -> R)
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [ ]:
# different tensor operations -> +, -, *, /, **
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
# .cat((x, y), dim) -> concatenate two tensors x, y, along the dimension (dim=0 is rows, dim=1 is cols)
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
# creating a binary tensor via logical statements
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# .sum() -> sums all elements in the tensor
X.sum()

tensor(66.)

In [ ]:
# broadcasting -> when you expand one/both tensors to allow for elementwise operations on the resulting tensors
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
# replicated matrix a along the columns, and matrix b along the rows to allow for matrix addition
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# memory allocation issue
before = id(Y)
Y = Y + X
id(Y) == before

False

In [ ]:
# .zeros_like(x) -> creating a matrix of zeroes of the same shape as matrix x
# performing an in-place operation
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 137086771323632
id(Z): 137086771323632


In [ ]:
# also performs in-place operation, as long as matrix is not reused in operation
before = id(X)
X += Y
id(X) == before

True

In [ ]:
A = X.numpy() # converting to NumPy array
B = torch.from_numpy(A) # converting to torch Tensor
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
# converting a size-1 tensor to a python scalar
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)