In [ ]:
# NAME: Alan Luo
# Assignment: NLA_2
# Date: 09/07/2023
# Section: LEC002

In [ ]:
import torch

In [ ]:
A = torch.tensor([[1, 2], [-2, 1], [3, -1]], dtype=torch.float32)

A

tensor([[ 1.,  2.],
        [-2.,  1.],
        [ 3., -1.]])

In [ ]:
# Question 1a
rank = torch.linalg.matrix_rank(A)

rank

tensor(2)

In [ ]:
u, s, v = torch.svd(A)

print(u)
print(s)
print(v)

tensor([[-8.1650e-02, -9.8995e-01],
        [ 5.7155e-01, -1.4142e-01],
        [-8.1650e-01, -2.9802e-08]])
tensor([3.8730, 2.2361])
tensor([[-0.9487, -0.3162],
        [ 0.3162, -0.9487]])


In [ ]:
# Question 1b
u, s, v = torch.svd(A)

print(f'svd u val: {u}')
print(f'svd s val: {s}')
print(f'svd v val: {v}\n')

K = int(s.shape[0])

print(f'K value: {K}\n')

u_i = []
s_i = []
v_i = []

for i in range(K):
  u_i.append(u[i])
  s_i.append(s[i])
  v_i.append(v[:, i])

print(f'u values: {u_i}')
print(f's values: {s_i}')
print(f'v values: {v_i}\n')

S = torch.diag(s)

print(f'u dims: {len(u)}x{len(u[0])}')
print(f's dims: {len(S)}x{len(S[0])}')
print(f'v dims: {len(v)}x{len(v[0])}')

svd u val: tensor([[-8.1650e-02, -9.8995e-01],
        [ 5.7155e-01, -1.4142e-01],
        [-8.1650e-01, -2.9802e-08]])
svd s val: tensor([3.8730, 2.2361])
svd v val: tensor([[-0.9487, -0.3162],
        [ 0.3162, -0.9487]])

K value: 2

u values: [tensor([-0.0816, -0.9899]), tensor([ 0.5715, -0.1414])]
s values: [tensor(3.8730), tensor(2.2361)]
v values: [tensor([-0.9487,  0.3162]), tensor([-0.3162, -0.9487])]

u dims: 3x2
s dims: 2x2
v dims: 2x2


In [ ]:
# Question 1c
B = torch.matmul(A, A.T)
print(f'B Matrix: {B}\n')

l, v = torch.linalg.eig(B)

print(f'svd l val: {l}')
print(f'svd v val: {v}\n')

M = len(B)
print(f'M value: {M}\n')

w_i = []
l_i = []

for i in range(M):
  w_i.append(v[:, i])
  l_i.append(l[i])

print(f'w values: {w_i}')
print(f'l values: {l_i}')

B Matrix: tensor([[ 5.,  0.,  1.],
        [ 0.,  5., -7.],
        [ 1., -7., 10.]])

svd l val: tensor([ 1.5000e+01+0.j,  5.0000e+00+0.j, -9.5980e-08+0.j])
svd v val: tensor([[ 8.1650e-02+0.j,  9.8995e-01+0.j,  1.1547e-01+0.j],
        [-5.7155e-01+0.j,  1.4142e-01+0.j, -8.0829e-01+0.j],
        [ 8.1650e-01+0.j, -1.7136e-07+0.j, -5.7735e-01+0.j]])

M value: 3

w values: [tensor([ 0.0817+0.j, -0.5715+0.j,  0.8165+0.j]), tensor([ 9.8995e-01+0.j,  1.4142e-01+0.j, -1.7136e-07+0.j]), tensor([ 0.1155+0.j, -0.8083+0.j, -0.5774+0.j])]
l values: [tensor(15.0000+0.j), tensor(5.+0.j), tensor(-9.5980e-08+0.j)]
