In [ ]:
# NAME: Alan Luo
# Assignment: NLA_1 - 2.3.1 to 2.3.4 Linear Algebra
# Date: 09/07/2023
# Section: LEC002

In [ ]:
import torch

In [ ]:
# .tensor(x) -> assigning two tensor scalars x, y, and performing operations on them
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [ ]:
# .arange(3) -> creating a vector
x = torch.arange(3)
x

tensor([0, 1, 2])

In [ ]:
# use indexing to access elements in the vector
x[2]

tensor(2)

In [ ]:
# len(x) -> grab dimensionality of vector x
len(x)

3

In [ ]:
# .shape -> access the size of the attribute, shape is a tuple that indicates length along each axis
x.shape

torch.Size([3])

In [ ]:
# reshaping a matrix to be 3x2
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
# transposing the matrix
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
# check if matrix is symmetric (when A=A.T)
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
# tensor with dimensions (height, weight, channel)
torch.arange(24).reshape(2, 3, 4)